# Generated by Django 3.2.15 on 2022-09-12 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foods', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='breakfast',
            options={'ordering': ('date',), 'verbose_name_plural': 'Breakfast'},
        ),
        migrations.AlterModelOptions(
            name='snacks',
            options={'ordering': ('date',), 'verbose_name_plural': 'Snacks'},
        ),
        migrations.AddField(
            model_name='breakfast',
            name='image',
            field=models.URLField(default='https://images.unsplash.com/photo-1568901346375-23c9450c58cd?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxzZWFyY2h8MXx8YnVyZ2VyfGVufDB8fDB8fA%3D%3D&w=1000&q=80', max_length=1000),
        ),
        migrations.AddField(
            model_name='snacks',
            name='image',
            field=models.URLField(default='https://images.unsplash.com/photo-1568901346375-23c9450c58cd?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxzZWFyY2h8MXx8YnVyZ2VyfGVufDB8fDB8fA%3D%3D&w=1000&q=80', max_length=1000),
        ),
    ]
